#!/usr/bin/env python3
"""Consume OpenSTA time-power stdout, show progress, write power VCD (+ CSV).

Reads markers from power_time_sta.tcl:
  ===WINDOW i=== / ===INST u_imem=== / ===INST u_dmem=== / ===ENDWINDOW i===

Hierarchy (depth=1, flat post-PnR netlist):
  top, u_imem, u_dmem, logic(=top-macros)  — each with total_uW + static_uW
"""
from __future__ import annotations

import argparse
import csv
import json
import re
import sys
import time
from pathlib import Path


def _nums(line: str) -> list[float]:
    return [float(x) for x in re.findall(r"[-+]?\d*\.\d+(?:[eE][-+]?\d+)?|\d+", line)]


def parse_group_leakage_total(text: str) -> tuple[float | None, float | None]:
    """Return (leakage_w, total_w) from a report_power group table."""
    m = re.search(
        r"^\s*Total\s+([-+0-9.eE+\s]+?)(?:\s+[\d.]+%\s*)?$",
        text,
        re.I | re.M,
    )
    if not m:
        return None, None
    nums = _nums(m.group(1))
    if len(nums) >= 4:
        return nums[2], nums[3]
    if nums:
        return None, nums[-1]
    return None, None


def parse_instance_leakage_total(text: str, inst: str) -> tuple[float | None, float | None]:
    """Parse single-instance report_power line."""
    for line in text.splitlines():
        if re.search(rf"\b{re.escape(inst)}\b", line):
            nums = _nums(line)
            if len(nums) >= 4:
                return nums[2], nums[3]
            if nums:
                return None, nums[-1]
    return None, None


def watts_to_uw(w: float | None) -> int:
    if w is None:
        return 0
    return max(0, int(round(w * 1e6)))


def _progress_bar(i: int, n: int, t0: float, last_top_uw: int) -> None:
    done = i + 1
    pct = 100.0 * done / n if n else 100.0
    elapsed = max(time.time() - t0, 1e-6)
    rate = done / elapsed
    eta = (n - done) / rate if rate > 0 else 0.0
    width = 28
    fill = int(width * done / n) if n else width
    bar = "#" * fill + "-" * (width - fill)
    eta_m, eta_s = divmod(int(eta), 60)
    msg = (
        f"\r  [{bar}] {done}/{n} ({pct:5.1f}%)  "
        f"{rate:.2f} win/s  ETA {eta_m}m{eta_s:02d}s  "
        f"top={last_top_uw} uW   "
    )
    print(msg, end="", file=sys.stderr, flush=True)


def write_power_vcd(
    path: Path,
    *,
    timescale: str,
    rows: list[dict],
) -> None:
    """Stairstep integer µW signals for GTKWave / Surfer."""
    signals = [
        "window_idx",
        "top_total_uW",
        "top_static_uW",
        "u_imem_total_uW",
        "u_imem_static_uW",
        "u_dmem_total_uW",
        "u_dmem_static_uW",
        "logic_total_uW",
        "logic_static_uW",
    ]
    # Single-char-ish ids; keep printable ASCII.
    ids = [chr(33 + i) for i in range(len(signals))]  # ! " # ...

    def bint(val: int, width: int = 32) -> str:
        v = max(0, min(val, (1 << width) - 1))
        return "b" + format(v, f"0{width}b")

    lines: list[str] = [
        "$date",
        f"\tgenerated by emit_time_power.py",
        "$end",
        "$version",
        "\tskywater time-based power",
        "$end",
        "$timescale",
        f"\t{timescale}",
        "$end",
        "$scope module power_trace $end",
    ]
    for sid, name in zip(ids, signals):
        lines.append(f"$var integer 32 {sid} {name} $end")
    lines += ["$upscope $end", "$enddefinitions $end"]

    prev: dict[str, int] | None = None
    for row in rows:
        t = int(row["t0"])
        cur = {k: int(row[k]) for k in signals}
        lines.append(f"#{t}")
        if prev is None:
            for sid, name in zip(ids, signals):
                lines.append(f"{bint(cur[name])} {sid}")
        else:
            for sid, name in zip(ids, signals):
                if cur[name] != prev[name]:
                    lines.append(f"{bint(cur[name])} {sid}")
        prev = cur

    # Hold last value until end of last window.
    if rows:
        lines.append(f"#{int(rows[-1]['t1'])}")

    path.write_text("\n".join(lines) + "\n")


def write_csv(path: Path, rows: list[dict]) -> None:
    fields = [
        "index",
        "t0",
        "t1",
        "window_idx",
        "top_total_uW",
        "top_static_uW",
        "u_imem_total_uW",
        "u_imem_static_uW",
        "u_dmem_total_uW",
        "u_dmem_static_uW",
        "logic_total_uW",
        "logic_static_uW",
    ]
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        for row in rows:
            w.writerow(row)


def consume_sta_stream(
    stream,
    windows_meta: list[dict],
) -> list[dict]:
    n = len(windows_meta)
    rows: list[dict] = []
    mode = None
    buf: list[str] = []
    cur_i: int | None = None
    top_l = top_t = None
    imem_l = imem_t = None
    dmem_l = dmem_t = None
    t0 = time.time()
    last_top = 0

    def flush_section() -> None:
        nonlocal top_l, top_t, imem_l, imem_t, dmem_l, dmem_t, buf, mode
        text = "\n".join(buf)
        buf = []
        if mode == "window":
            top_l, top_t = parse_group_leakage_total(text)
        elif mode == "imem":
            imem_l, imem_t = parse_instance_leakage_total(text, "u_imem")
        elif mode == "dmem":
            dmem_l, dmem_t = parse_instance_leakage_total(text, "u_dmem")
        mode = None

    for raw in stream:
        line = raw.rstrip("\n")
        # Mirror STA noise lightly? keep stdout clean — only progress on stderr.
        if line.startswith("TIME_POWER_WINDOWS"):
            print(f"==> OpenSTA time-power ({line.split()[-1]} windows)", file=sys.stderr)
            continue
        if line.startswith("===WINDOW "):
            flush_section()
            cur_i = int(line[len("===WINDOW ") :].strip().strip("=").strip())
            top_l = top_t = imem_l = imem_t = dmem_l = dmem_t = None
            mode = "window"
            buf = []
            continue
        if line.startswith("===INST u_imem"):
            flush_section()
            mode = "imem"
            buf = []
            continue
        if line.startswith("===INST u_dmem"):
            flush_section()
            mode = "dmem"
            buf = []
            continue
        if line.startswith("===ENDWINDOW"):
            flush_section()
            assert cur_i is not None
            meta = windows_meta[cur_i]
            top_total = watts_to_uw(top_t)
            top_static = watts_to_uw(top_l)
            imem_total = watts_to_uw(imem_t)
            imem_static = watts_to_uw(imem_l)
            dmem_total = watts_to_uw(dmem_t)
            dmem_static = watts_to_uw(dmem_l)
            logic_total = max(0, top_total - imem_total - dmem_total)
            logic_static = max(0, top_static - imem_static - dmem_static)
            row = {
                "index": cur_i,
                "t0": meta["t0"],
                "t1": meta["t1"],
                "window_idx": cur_i,
                "top_total_uW": top_total,
                "top_static_uW": top_static,
                "u_imem_total_uW": imem_total,
                "u_imem_static_uW": imem_static,
                "u_dmem_total_uW": dmem_total,
                "u_dmem_static_uW": dmem_static,
                "logic_total_uW": logic_total,
                "logic_static_uW": logic_static,
            }
            rows.append(row)
            last_top = top_total
            _progress_bar(cur_i, n, t0, last_top)
            mode = None
            continue
        if line.startswith("TIME_POWER_DONE"):
            flush_section()
            continue
        if mode is not None:
            buf.append(line)

    print(file=sys.stderr)  # finish progress line
    if len(rows) != n:
        print(
            f"WARNING: expected {n} windows, got {len(rows)}",
            file=sys.stderr,
        )
    return rows


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--windows-json", type=Path, required=True)
    ap.add_argument("--vcd-out", type=Path, required=True)
    ap.add_argument("--csv-out", type=Path, default=None)
    ap.add_argument("--summary-out", type=Path, default=None)
    ap.add_argument(
        "--sta-log",
        type=Path,
        default=None,
        help="If set, read this file instead of stdin",
    )
    args = ap.parse_args()

    meta = json.loads(args.windows_json.read_text())
    windows = meta["windows"]
    timescale = meta.get("timescale") or "1ns"

    if args.sta_log:
        stream = args.sta_log.open("r", errors="replace")
    else:
        stream = sys.stdin

    try:
        rows = consume_sta_stream(stream, windows)
    finally:
        if args.sta_log:
            stream.close()

    args.vcd_out.parent.mkdir(parents=True, exist_ok=True)
    write_power_vcd(args.vcd_out, timescale=timescale, rows=rows)
    print(f"wrote {args.vcd_out}", file=sys.stderr)

    csv_path = args.csv_out or args.vcd_out.with_suffix(".csv")
    write_csv(csv_path, rows)
    print(f"wrote {csv_path}", file=sys.stderr)

    if rows:
        tops = [r["top_total_uW"] for r in rows]
        peak_i = max(range(len(tops)), key=lambda i: tops[i])
        avg = sum(tops) / len(tops)
        summary = [
            "Time-based power summary (activity / OpenSTA, µW)",
            f"vcd_source     : {meta.get('vcd')}",
            f"n_windows      : {len(rows)}",
            f"timescale      : {timescale}",
            f"t_range        : {meta.get('t_start')} .. {meta.get('t_end')}",
            f"top_avg_uW     : {avg:.1f}",
            f"top_peak_uW    : {tops[peak_i]}  (window {peak_i}, "
            f"t=[{rows[peak_i]['t0']},{rows[peak_i]['t1']}))",
            f"top_min_uW     : {min(tops)}",
            f"power_vcd      : {args.vcd_out}",
            f"power_csv      : {csv_path}",
            "",
            "Blocks (depth=1): top, u_imem, u_dmem, logic(=top-macros).",
            "static = OpenSTA Leakage; total = OpenSTA Total.",
            "Sleep: core ICG GATE case-analyzed from VCD sram_clk_en duty.",
        ]
        text = "\n".join(summary) + "\n"
        summary_path = args.summary_out or args.vcd_out.with_name("power_time_summary.txt")
        summary_path.write_text(text)
        print(text)


if __name__ == "__main__":
    main()
