#!/usr/bin/env python3
"""Generate $deposit statements to zero the synthesized VexRiscv regfile.

RTL loads VexRiscv2.v_toplevel_RegFilePlugin_regFile.bin (all zeros).
Post-synth flops start as X; without this, reads of x0 poison the datapath.
"""
from __future__ import annotations

import argparse
from pathlib import Path


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out", type=Path, required=True)
    ap.add_argument("--scope", default="u_soc", help="Instance path to sky130_vex2_soc")
    args = ap.parse_args()

    lines = [
        "// Auto-generated by gen_gls_regfile_init.py — do not edit.",
        "// Zeros gate-level RegFilePlugin_regFile[*][*] (and read ports).",
        "initial begin",
    ]
    scope = args.scope
    for r in range(32):
        for b in range(32):
            lines.append(
                f"  $deposit({scope}.\\u_cpu.RegFilePlugin_regFile[{r}][{b}] , 1'b0);"
            )
    for port in (0, 1):
        for b in range(32):
            lines.append(
                f"  $deposit({scope}.\\u_cpu.RegFilePlugin_regFile_spinal_port{port}[{b}] , 1'b0);"
            )
    lines.append("  $display(\"GLS: deposited 0 into CPU regfile + read ports\");")
    lines.append("end")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
