#!/usr/bin/env python3
"""Generate OpenLane explore configs and print a placement plan.

SRAM22 2048x32 is 674.48 x 781.92 µm. Two instances side-by-side dominate area.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

SRAM_W = 674.48
SRAM_H = 781.92

ROOT = Path(__file__).resolve().parents[1]  # hardening/
DES = ROOT / "sky130_vex2_soc"
BASE = DES / "config.json"
# Keep configs beside the design so dir:: relative paths stay valid.
OUT_DIR = DES


def place(die_w: float, die_h: float, margin: float, gap: float) -> dict:
    """Left/right SRAM placement; stdcells use the center channel + margins."""
    imem = (margin, margin)
    dmem_x = margin + SRAM_W + gap
    dmem = (dmem_x, margin)
    right = dmem_x + SRAM_W
    top = margin + SRAM_H
    if right + margin > die_w + 1e-6:
        raise SystemExit(
            f"die_w={die_w} too small: macros need {right + margin:.1f} µm"
        )
    if top + margin > die_h + 1e-6:
        raise SystemExit(
            f"die_h={die_h} too small: macros need {top + margin:.1f} µm"
        )
    return {
        "DIE_AREA": [0, 0, die_w, die_h],
        "CORE_AREA": [margin / 2, margin / 2, die_w - margin / 2, die_h - margin / 2],
        "imem": imem,
        "dmem": dmem,
        "channel_um2": gap * SRAM_H,
        "macro_bbox": [margin, margin, right, top],
    }


def make_config(
    *,
    period: float,
    die_w: float,
    die_h: float,
    margin: float,
    gap: float,
    density: float,
) -> dict:
    base = json.loads(BASE.read_text())
    p = place(die_w, die_h, margin, gap)
    base["CLOCK_PERIOD"] = period
    halo = max(20.0, margin / 2)
    base["DIE_AREA"] = p["DIE_AREA"]
    base["CORE_AREA"] = [halo, halo, die_w - halo, die_h - halo]
    base["PL_TARGET_DENSITY_PCT"] = density
    # Exploration: stop interest at STA; keep signoff skips from base.
    base["RUN_IRDROP_REPORT"] = False
    base["RUN_MAGIC_STREAMOUT"] = False
    base["RUN_MAGIC_DRC"] = False
    base["RUN_KLAYOUT_XOR"] = False
    base["RUN_LVS"] = False
    base["MAGIC_CAPTURE_ERRORS"] = False
    base["ERROR_ON_ILLEGAL_OVERLAPS"] = False
    base["ERROR_ON_PDN_VIOLATIONS"] = False
    base["GRT_ALLOW_CONGESTION"] = True
    macros = base["MACROS"]["sram22_2048x32m8w8"]["instances"]
    macros["u_imem"]["location"] = [round(p["imem"][0], 3), round(p["imem"][1], 3)]
    macros["u_dmem"]["location"] = [round(p["dmem"][0], 3), round(p["dmem"][1], 3)]
    # OpenLane rejects unknown keys — keep meta out of the JSON we write.
    meta = {
        "gap_um": gap,
        "margin_um": margin,
        "die_mm2": (die_w * die_h) / 1e6,
        "channel_um2": p["channel_um2"],
        "note": "Generated by hardening/scripts/explore_area_fmax.py",
    }
    base["_meta"] = meta  # stripped before write
    return base


# Named experiments: shrink area around macro floor; push period near SS period_min.
EXPERIMENTS = {
    # Current-ish but slightly tighter height (reference).
    "ref_2200x1800_p28": dict(die_w=2200, die_h=1800, margin=80, gap=500, period=28, density=40),
    # Compact: ~200 µm channel (stdcell area ~218k fits in gap*H≈156k at high dens + margins).
    "area_1750x1000_p28": dict(die_w=1750, die_h=1000, margin=40, gap=200, period=28, density=45),
    "area_1680x950_p28": dict(die_w=1680, die_h=950, margin=40, gap=150, period=28, density=50),
    "area_1620x920_p28": dict(die_w=1620, die_h=920, margin=35, gap=120, period=28, density=55),
    # Fmax push on a medium die (not the loosest, not the tightest).
    "fmax_1800x1100_p18": dict(die_w=1800, die_h=1100, margin=50, gap=250, period=18, density=45),
    "fmax_1800x1100_p15": dict(die_w=1800, die_h=1100, margin=50, gap=250, period=15, density=45),
}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="Write JSON configs under explore/")
    ap.add_argument("--list", action="store_true", help="Print experiment table")
    ap.add_argument("names", nargs="*", help="Subset of experiment names")
    args = ap.parse_args()

    names = args.names or list(EXPERIMENTS)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    rows = []
    for name in names:
        if name not in EXPERIMENTS:
            raise SystemExit(f"unknown experiment {name}; choose from {list(EXPERIMENTS)}")
        kw = EXPERIMENTS[name]
        cfg = make_config(**kw)
        meta = cfg.pop("_meta")
        die_w, die_h = kw["die_w"], kw["die_h"]
        rows.append(
            (
                name,
                die_w,
                die_h,
                meta["die_mm2"],
                kw["gap"],
                kw["period"],
                1000.0 / kw["period"],
            )
        )
        if args.write:
            path = OUT_DIR / f"explore_{name}.json"
            path.write_text(json.dumps(cfg, indent=2) + "\n")
            print(f"wrote {path}")

    if args.list or not args.write:
        print(f"{'name':28} {'W':>6} {'H':>6} {'mm2':>6} {'gap':>5} {'Tns':>5} {'MHz':>6}")
        for r in rows:
            print(f"{r[0]:28} {r[1]:6.0f} {r[2]:6.0f} {r[3]:6.3f} {r[4]:5.0f} {r[5]:5.1f} {r[6]:6.1f}")
        # Macro floor
        floor = (2 * SRAM_W * SRAM_H) / 1e6
        print(f"\nMacro-only floor: {floor:.3f} mm2 (2 x {SRAM_W}x{SRAM_H})")
        print(f"v2 baseline die:  3.960 mm2; post-PnR period_min SS≈27.8ns (~36 MHz), TT≈13.9ns (~72 MHz)")


if __name__ == "__main__":
    main()
